### ISSUE TITLE
关于PaddleOCR运行报错的问题。

### ISSUE THREAD

**Issue by eastmoe** [eastmoe/Germen#1]
希望有人能给咱提供一些有关如何解决这个报错的帮助。虽然目前不影响运行，但是心里感觉不太舒服。
![Error.PNG](https://s2.loli.net/2023/03/07/G7MVphm6XlO4NdW.png)

E:\个人文件\Documents\GITHUB\Germen_env\lib\site-packages\pkg_resources\__init__.py:2804: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
E:\个人文件\Documents\GITHUB\Germen_env\lib\site-packages\pkg_resources\__init__.py:2804: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
E:\个人文件\Documents\GITHUB\Germen_env\lib\site-packages\pkg_resources\__init__.py:2804: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
E:\个人文件\Documents\GITHUB\Germen_env\lib\site-packages\_distutils_hack\__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
本次图片转文字开始时间： 2023-03-07 09:36:32.455663

**Comment by sichaolong** [comment]
按照报错找到 warnings.warn("Setuptools is replacing distutils.") 这块，然后注释掉就行了，不行的话在找调用这个方法的方法里面有个if判断，注释掉检查代码然后换成pass即可

**Comment by eastmoe** [comment]
好的，我试试。

**Comment by eastmoe** [comment]
可以，算是解决了。
