### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by ghost** [eastmoe/Germen#2]
都按着步骤来的但是一直提示ModuleNotFoundError: No module named 'paddle_fluid'，这要怎么解决啊

**Comment by ghost** [comment]
我看网上好像说的只有2.0以下版本paddlepaddle有这个文件，但是我看官网能安装的最低也是2.3，这个要怎么办啊大佬。

**Comment by eastmoe** [comment]
最近Github账户的双重认证丢了....好久才看到这个issue，估计是更新之后导致了不兼容，我过一段时间修改一下代码试试看吧。

**Comment by eastmoe** [comment]
@a464679590 我重新写了OCR模块并且更新了安装流程，你再试试看。
